#ifndef STRINGUTIL_INTERFACE_1604911737496_H
#define STRINGUTIL_INTERFACE_1604911737496_H
#include "ccglobal/export.h"

#if USE_STRINGUTIL_DLL
	#define STRINGUTIL_API CC_DECLARE_IMPORT
#elif USE_STRINGUTIL_STATIC
	#define STRINGUTIL_API CC_DECLARE_STATIC
#else
	#if STRINGUTIL_DLL
		#define STRINGUTIL_API CC_DECLARE_EXPORT
	#else
		#define STRINGUTIL_API CC_DECLARE_STATIC
	#endif
#endif

#endif // STRINGUTIL_INTERFACE_1604911737496_H